name: crypto_stats
description: An application that shows current prices for famous cryptocurrencies.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.3 <2.7.0"

dependencies:
  cached_network_image: ^3.1.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_gen_runner: ^3.1.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter_icons:
  image_path: "assets/images/flutter_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800

flutter_gen:
  # By default, the generate files are in `lib/gen/`
  output: lib/generated
